src/Entity/Weight.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\WeightRepository")
 */
class Weight
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $value;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Product", mappedBy="weight")
     */
    private $products;

    public function __construct()
    {
        $this->createdAt = new \DateTime();
        $this->updatedAt = new \DateTime();
        $this->products = new ArrayCollection();
    }

    public function __toString() {
        return (string) $this->getConvert();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getValue(): ?int
    {
        return $this->value;
    }

    public function setValue(int $value): self
    {
        $this->value = $value;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getConvert()
    {

        if($this->getValue() > 999 ){
            $res = $this->getValue()/1000;
            $res = round($res,2);
            return $res.' kg';
        }

        return $this->getValue().' g';
    }

    /**
     * @return Collection|Product[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setWeight($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->products->contains($product)) {
            $this->products->removeElement($product);
            // set the owning side to null (unless already changed)
            if ($product->getWeight() === $this) {
                $product->setWeight(null);
            }
        }

        return $this;
    }
}

src/Controller/back/CaracteristiqueController.php
<?php

namespace App\Controller\back;

use App\Entity\Product;
use App\Entity\Caracteritique;
use App\Form\ProductType;
use App\Entity\Caracteristique;

use App\Entity\TitleCaracteristique;
use App\Repository\ProductRepository;
use App\Repository\CaracteristiquetRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\TitleCaracteristiqueRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/admin/produit")
 */
class CaracteristiqueController extends AbstractController
{
    /**
     * @Route("/{id}/caracteristique/liste/", name="admin_caracteristique_search", methods="GET")
     */
    public function search(TitleCaracteristiqueRepository $titleCaracteristiqueRepository,Product $product): Response
    {
        return $this->render('back/caracteristique/search.html.twig', [
            'titleCaracts' => $titleCaracteristiqueRepository->findBy(['product'=>$product]), 
            'slug'=>'admin_category', 
        ]);
    }

     /**
     * @Route("/caracteristique/create", name="admin_caracteristique_create", methods="GET|POST")
     */
    public function create(Request $request,TitleCaracteristiqueRepository $titleCaracteristiqueRepositoryi): Response
    {        

        
        $titleCaracteristique = new TitleCaracteristique();
        $form = $this->createForm(ProductType::class, $titleCaracteristique, [
            'update' => $titleCaracteristique->getId()==null?false:true,
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($titleCaracteristique);
            $em->flush();

            return $this->redirectToRoute('admin_caracteristique_search');
        }

        return $this->render('back/caracteristique/create.html.twig', [
            'titleCaracteristique' => $titleCaracteristique,
            'form' => $form->createView(),
            'slug' => 'admin_product',
        ]);
    }
}

src/Controller/back/CategoryController.php
<?php

namespace App\Controller\back;

use App\Entity\Category;
use App\Form\CategoryType;
use App\Repository\CategoryRepository;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/category")
 */
class CategoryController extends AbstractController
{
    /**
     * @Route("/", name="admin_category_search", methods="GET")
     */
    public function search(CategoryRepository $categoryRepository): Response
    {
        return $this->render('back/category/search.html.twig', [
            'categories' => $categoryRepository->findAll(), 
            'slug'=>'admin_category', 
        ]);
    }

    /**
     * @Route("/create", name="admin_category_create", methods="GET|POST")
     */
    public function create(Request $request): Response
    {
        $category = new Category();
        $form = $this->createForm(CategoryType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($category);
            $em->flush();

            return $this->redirectToRoute('admin_category_search');
        }

        return $this->render('back/category/create.html.twig', [
            'category' => $category,
            'form' => $form->createView(),
            'slug'=>'admin_category',
        ]);
    }

    /**
     * @Route("/{id}", name="admin_category_read", methods="GET")
     */
    public function read(Category $category): Response
    {
        return $this->render('back/category/read.html.twig', [
        'category' => $category, 
            'slug'=>'admin_category',
        ]);
    }

    /**
     * @Route("/update/{id}", name="admin_category_update", methods="GET|POST")
     */
    public function update(Request $request, Category $category): Response
    {
        $form = $this->createForm(CategoryType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('admin_category_search');
        }

        return $this->render('back/category/update.html.twig', [
            'category' => $category,
            'form' => $form->createView(),
            'slug'=>'admin_category',
        ]);
    }

    /**
     * @Route("/delete/{id}", name="admin_category_delete", methods="DELETE")
     */
    public function delete(Request $request, Category $category): Response
    {
            $msg = 'Enregistrement supprimé avec succès';
            $em = $this->getDoctrine()->getManager();
            $em->remove($category);
            $em->flush();
            $this->addFlash('success', $msg);
            return $this->redirectToRoute('admin_category_search');
    }
}

src/Controller/back/CommandController.php
<?php

namespace App\Controller\back;

use App\Entity\Command;
use App\Form\CommandType;
use App\Repository\CommandRepository;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/command")
 */
class CommandController extends AbstractController
{
    /**
     * @Route("/", name="admin_command_search", methods="GET")
     */
    public function search(CommandRepository $commandRepository): Response
    {
        return $this->render('back/command/search.html.twig', [
            'commands' => $commandRepository->findAll(), 
            'slug'=>'admin_command', 
        ]);
    }

    /**
     * @Route("/{id}", name="admin_command_read", methods="GET")
     */
    public function read(Command $command): Response
    {
        return $this->render('back/command/read.html.twig', [
        'command' => $command, 
            'slug'=>'admin_command',
        ]);
    }
/**
     * @Route("/update/{id}", name="admin_command_update", methods="GET|POST")
     */
    public function update(Request $request,Command $command): Response
    {
        $form = $this->createForm(CommandType::class, $command);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('admin_command_search');
        }

        return $this->render('back/command/update.html.twig', [
            'command' => $command,
            'form' => $form->createView(),
            'slug'=>'admin_command',
        ]);
    }

    /**
     * @Route("/delete/{id}", name="admin_command_delete", methods="DELETE")
     */
    public function delete(Request $request, Command $command): Response
    {
            $msg = 'Enregistrement supprimé avec succès';
            $em = $this->getDoctrine()->getManager();
            $em->remove($command);
            $em->flush();
            $this->addFlash('success', $msg);
            return $this->redirectToRoute('admin_command_search');
    }
}

src/Controller/back/ConfigurationController.php
<?php

namespace App\Controller\back;

use App\Entity\Configuration;
use App\Form\ConfigurationType;
use App\Repository\ConfigurationRepository;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/admin/configuration")
 */
class ConfigurationController extends AbstractController
{
    /**
     * @Route("/", name="admin_configuration_search", methods="GET")
     */
    public function search(ConfigurationRepository $configurationRepository): Response
    {
        return $this->render('back/configuration/search.html.twig', [
            'configurations' => $configurationRepository->findAll(),
            'slug' => 'config',
        ]);
    }

    /**
     * @IsGranted("ROLE_SUPER_ADMIN")
     * @Route("/create", name="admin_configuration_create", methods="GET|POST")
     */
    public function create(Request $request): Response
    {
        $configuration = new Configuration();
        $form = $this->createForm(ConfigurationType::class, $configuration);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($configuration);
            $em->flush();

            return $this->redirectToRoute('admin_configuration_search');
        }

        return $this->render('back/configuration/create.html.twig', [
            'configuration' => $configuration,
            'form' => $form->createView(),
            'slug' => 'config',
        ]);
    }

    /**
     * @Route("/{id}", name="admin_configuration_read", methods="GET")
     */
    public function read(Configuration $configuration): Response
    {
        return $this->render('back/configuration/read.html.twig', [
            'configuration' => $configuration,
            'slug' => 'config',
        ]);
    }

    /**
     * @Route("/update/{id}", name="admin_configuration_update", methods="GET|POST")
     */
    public function update(Request $request, Configuration $configuration): Response
    {
        $form = $this->createForm(ConfigurationType::class, $configuration);

        if (!$this->isGranted('ROLE_SUPER_ADMIN')) {
            $form->remove('name');
        }
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('admin_configuration_search');
        }

        return $this->render('back/configuration/update.html.twig', [
            'configuration' => $configuration,
            'form' => $form->createView(),
            'slug' => 'config',
        ]);
    }

    /**
     * @Route("/delete/{id}", name="admin_configuration_delete", methods="DELETE")
     */
    public function delete(Request $request, Configuration $configuration): Response
    {
            $msg = 'Enregistrement supprimé avec succès';
            $em = $this->getDoctrine()->getManager();
            $em->remove($configuration);
            $em->flush();
            $this->addFlash('success', $msg);
            return $this->redirectToRoute('admin_configuration_search');
    }
}

src/Controller/back/ContactController.php
<?php

namespace App\Controller\back;

use App\Entity\Contact;
use App\Form\ContactType;
use App\Repository\ContactRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/admin/contact")
 */
class ContactController extends AbstractController
{
    /**
     * @Route("/", name="admin_contact_search", methods="GET")
     */
    public function search(ContactRepository $contactRepository): Response
    {
        return $this->render('back/contact/search.html.twig', [
            'contacts' => $contactRepository->findAll(), 
            'slug'=>'admin_contact', 
        ]);
    }

    // /**
    //  * @Route("/create", name="admin_category_create", methods="GET|POST")
    //  */
    // public function create(Request $request): Response
    // {
    //     $category = new Category();
    //     $form = $this->createForm(CategoryType::class, $category);
    //     $form->handleRequest($request);

    //     if ($form->isSubmitted() && $form->isValid()) {
    //         $em = $this->getDoctrine()->getManager();
    //         $em->persist($category);
    //         $em->flush();

    //         return $this->redirectToRoute('admin_category_search');
    //     }

    //     return $this->render('back/category/create.html.twig', [
    //         'category' => $category,
    //         'form' => $form->createView(),
    //         'slug'=>'admin_category',
    //     ]);
    // }

    /**
     * @Route("/{id}", name="admin_contact_read", methods="GET")
     */
    public function read(Contact $contact): Response
    {
        return $this->render('back/contact/read.html.twig', [
        'contact' => $contact, 
            'slug'=>'admin_category',
        ]);
    }

    // /**
    //  * @Route("/update/{id}", name="admin_category_update", methods="GET|POST")
    //  */
    // public function update(Request $request, Category $category): Response
    // {
    //     $form = $this->createForm(CategoryType::class, $category);
    //     $form->handleRequest($request);

    //     if ($form->isSubmitted() && $form->isValid()) {
    //         $this->getDoctrine()->getManager()->flush();

    //         return $this->redirectToRoute('admin_category_search');
    //     }

    //     return $this->render('back/category/update.html.twig', [
    //         'category' => $category,
    //         'form' => $form->createView(),
    //         'slug'=>'admin_category',
    //     ]);
    // }

    /**
     * @Route("/delete/{id}", name="admin_category_delete", methods="DELETE")
     */
    public function delete(Request $request, Contact $contact): Response
    {
            $msg = 'Message supprimé avec succès';
            $em = $this->getDoctrine()->getManager();
            $em->remove($contact);
            $em->flush();
            $this->addFlash('success', $msg);
            return $this->redirectToRoute('admin_contact_search');
    }
}

src/Controller/back/PagesController.php
<?php

namespace App\Controller\back;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PagesController extends AbstractController
{
    /**
     * @Route("/admin", name="admin")
     */
    public function index()
    {
        return $this->render('back/pages/index.html.twig', [
            'slug' => 'admin',
        ]);
    }
    /**
     * @Route("/espace-client", name="espace-client")
     */
    public function indexEspaceClient()
    {
        return $this->render('back/pages/index-espace-client.html.twig', [
            'slug' => 'espace-client',
        ]);
    }
    

    /**
     * @Route("/admin/fos-user-profile-show", name="fos_user_profile_show")
     */
    public function fos_user_profile_show()
    {
        return $this->redirectToRoute('admin');
    }
    
}

templates/back/weight/create.html.twig
{% extends 'back/layout.html.twig' %}

{% block title %} Ajouter {{'Weight'|transchoice(1)}} {% endblock %}

{% block content %}

<section class="section-padding">
    <div class="container">
        <h1>Ajouter {{'Weight'|transchoice(1)}}</h1>
        <div class="shape"></div>
        <div class="text-right mt-4">
            <a href="{{ path('admin_weight_search') }}" class="btn btn-primary" role="button">
                <i class="fa fa-reply"></i> Retour
            </a>
        </div>
        <div class="card mt-4 mb-4">
            <div class="card-header text-center">
                <h4>Formulaire {{'Weight'|transchoice(1)}}</h4>
            </div>
            <div class="card-content">
                {{ form_start(form) }}
                    {{ form_row(form.value) }}        
                    <br>
                    <button class="btn btn-primary">Ajouter</button>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/back/weight/read.html.twig
{% extends 'back/layout.html.twig' %}

{% block title %} Voir {{'Weight'|transchoice(1)}} {% endblock %}

{% block content %}

<section class="section-padding">
    <div class="container">
        <h1>Voir {{'Weight'|transchoice(1)}}</h1>
        <div class="shape"></div>

        <div class="text-right mt-4">
            <a href="{{ path('admin_weight_search') }}" class="btn btn-primary" role="button">
                <i class="fa fa-reply"></i> Retour
            </a>
        </div>
        <div class="card mt-4 mb-4">
            <div class="card-header text-center">
                <h4>Détail {{'Weight'|transchoice(1)}}</h4>
            </div>
            <div class="card-content">
                                    <div class="read-content">
                        <p>
                            <strong>{% trans %}Id{% endtrans %}</strong> : 
                            {{ weight.id }}
                        </p>
                    </div>
                                    <div class="read-content">
                        <p>
                            <strong>{% trans %}Value{% endtrans %}</strong> : 
                            {{ weight.value }}
                        </p>
                    </div>
                                    <div class="read-content">
                        <p>
                            <strong>{% trans %}CreatedAt{% endtrans %}</strong> : 
                            {{ weight.createdAt ? weight.createdAt|date('Y-m-d H:i:s') : '' }}
                        </p>
                    </div>
                                    <div class="read-content">
                        <p>
                            <strong>{% trans %}UpdatedAt{% endtrans %}</strong> : 
                            {{ weight.updatedAt ? weight.updatedAt|date('Y-m-d H:i:s') : '' }}
                        </p>
                    </div>
                            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/back/weight/search.html.twig
{% extends 'back/layout.html.twig' %}
{% block title %} Gestion {{'Weight'|transchoice(2)}} {% endblock %}

{% block content %}

{# ///////////////// MODAL DELETE ////////////////////#}
    <div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Suppression d'un enregistrement</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
              <form method="post" action="">
                    <input id="token" type="hidden" name="_token" value="">
                    <input type="hidden" name="_method" value="DELETE">
                    <button type="submit" class="btn btn-danger">Supprimer</button>
              </form>
            </div>
          </div>
        </div>
    </div>
{# ///////////////// END MODAL DELETE ////////////////////#}

<section class="section-padding">
    <div class="container">
        <h1>Gestion {{'Weight'|transchoice(2)}}</h1>
        <div class="shape"></div>

        <div class="text-right mt-4">
            <a href="{{ path('admin_weight_create') }}" class="btn btn-success">
                <i class="fa fa-plus" aria-hidden="true"></i> Ajouter {{'Weight'|transchoice(1)}}
            </a>
        </div>

        <div class="card mt-4 mb-4">
            <div class="card-header text-center">
                <h4>Liste {{'Weight'|transchoice(2)}}</h4>
            </div>
            <div class="card-content">
                <div class="table-responsive mt-4 mb-4">
                    <table class="table table-striped table-bordered" id="dataTable" width="100%" cellspacing="0" data-page-length='50'>
                        <thead>
                            <tr>
                                <th>{% trans %}Id{% endtrans %}</th>
                                <th>{% trans %}Value{% endtrans %}</th>
                                <th>{% trans %}CreatedAt{% endtrans %}</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for weight in weights %}
                            <tr>
                                <td>{{ weight.id }}</td>
                                <td>{{ weight.convert }}</td>
                                <td>{{ weight.createdAt ? weight.createdAt|date('d/m/Y') : '' }}</td>
                                <td>
                                    <a href="{{ path('admin_weight_read', {'id': weight.id}) }}" title="Voir" class="btn btn-primary" aria-label="Voir">
                                        <i class="fa fa-file"></i>
                                    </a>
                                    <a href="{{ path('admin_weight_update', {'id': weight.id}) }}" title="Modifier" class="btn btn-warning" aria-label="Modifier">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                    <a href="#" title="Supprimer" class="btn btn-danger btn-delete" data-toggle="modal" data-target="#delete" aria-label="Supprimer" id="{{weight.id}}" data-title="{{weight.value}}" data-path="{{ path('admin_weight_delete', {'id': weight.id})}}">
                                        <i class="fa fa-times"></i>
                                    </a>
                                </td>
                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="5">Aucun enregistrement</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('datatables/jquery.dataTables.js')}}"></script>
    <script src="{{ asset('datatables/dataTables.bootstrap4.js')}}"></script>
    <script>
            $(document).ready(function(){
                $(document).on ("click", ".btn-delete", function () {
                    var id = $(this).attr('id');
                    var title = $(this).attr('data-title');
                    var path = $(this).attr('data-path');
                    $('.modal-footer form').attr('action', path);
                    $('#token').val("{{ csrf_token('delete' ~"+id+") }}");
                    $('.modal-body').html("<p>Confirmez-vous la suppression de: <strong>"+title+"</strong></p>");
                });
            });
    </script>

    <script>
        $(document).ready(function(){$("#dataTable").DataTable()});
    </script>

    <script type="text/javascript">
        $('#dataTable').DataTable( {
            language: {
                processing:     "Traitement en cours...",
                search:         "Rechercher&nbsp;:",
                lengthMenu:    "Afficher _MENU_ &eacute;l&eacute;ments",
                info:           "Affichage de l'&eacute;lement _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
                infoEmpty:      "Affichage de l'&eacute;lement 0 &agrave; 0 sur 0 &eacute;l&eacute;ments",
                infoFiltered:   "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
                infoPostFix:    "",
                loadingRecords: "Chargement en cours...",
                zeroRecords:    "Aucun &eacute;l&eacute;ment &agrave; afficher",
                emptyTable:     "Aucune donnée disponible dans le tableau",
                paginate: {
                    first:      "Premier",
                    previous:   "Pr&eacute;c&eacute;dent",
                    next:       "Suivant",
                    last:       "Dernier"
                },
                aria: {
                    sortAscending:  ": activer pour trier la colonne par ordre croissant",
                    sortDescending: ": activer pour trier la colonne par ordre décroissant"
                }
            },

            aaSorting: []
        } );
    </script>
{% endblock %}

templates/back/weight/update.html.twig
{% extends 'back/layout.html.twig' %}

{% block title %} Modifier {{'Weight'|transchoice(1)}} {% endblock %}

{% block content %}

<section class="section-padding">
    <div class="container">
        <h1>Modifier {{'Weight'|transchoice(1)}}</h1>
        <div class="shape"></div>

        <div class="text-right mt-4">
            <a href="{{ path('admin_weight_search') }}" class="btn btn-primary" role="button">
                <i class="fa fa-reply"></i> Retour
            </a>
        </div>
        <div class="card mt-4 mb-4">
            <div class="card-header text-center">
                <h4>Formulaire {{'Weight'|transchoice(1)}}</h4>
            </div>
            <div class="card-content">
                {{ form_start(form) }}
                {{ form_row(form.value) }}        
                <br>
                <button class="btn btn-primary">Modifier</button>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
</section>
{% endblock %}